// قاموس أسماء اللاعبين - الجزء 1
window.playerNames = {
  "Francisco Trincão": "فرانسيسكو ترينتساو",
  "Eduard Spertsyan": "إدوارد سبيرتسيان",
  "Feras Al-Brikan": "فراس البريكان",
  "Meshal Ibrahim Al Mutairi": "مشعل إبراهيم المطيري",
  "Galeno": "جالينو",
  "Saeed Baattia": "سعيد باطيا",
  "Édouard Mendy": "إدوار ميندي",
  "Ivan Toney": "إيفان توني",
  "Artem Bondarenko": "أرتيم بوندارينكو",
  "Matheus Gonçalves": "ماثيوس غونسالفيس",
  "Abdullah Radif": "عبدالله رديف",
  "Ibrahin Montasser Azzam": "إبراهيم منتصر عزام",
  "Abubacarr Kinteh": "أبوبكار كينته",
  "Faisal Ibrahim Ahmed Fallatah": "فيصل إبراهيم أحمد فلاتة",
  "Ali Majrashi": "علي المجراشي",
  "Merih Demiral": "ميريح ديميرال",
  "Mohammed Yousef": "محمد يوسف",
  "Ziyad Al-Johani": "زياد الجهني",
  "Saad Balobaid": "سعد بلوبيد",
  "Osamah Al Daghmah": "أسامة الدغمة",
  "Wael Khalid Al Johani": "وائل خالد الجهني",
  "Ziyad Mallah": "زياد الملا",
  "Mouhamadou Makhtar Diop": "محمدو مختار ديوب",
  "Rayane Hamidou": "رايان حميدو",
  "Waheb Saleh": "وهب صالح",
  "Salem Abdullah": "سالم عبدالله",
  "Abdullah Abdo": "عبدالله عبدو",
  "Naif Masoud": "نايف مسعود",
  "Salman Al-Jadani": "سلمان الجداني",
  "Ramez Al Attar": "رامز العطار",
  "Mailson": "ميلسون",
  "Pape Mustapha Samb": "بابي مصطفى سامب",
  "Zineddine Belaïd": "زين الدين بلعيد",
  "Mohammed Al Hurayji": "محمد الحريجي",
  "Mohammed Al Kuwaykibi": "محمد الكويكبي",
  "Parfait Guiagon": "بارفيه جياجون",
  "Abderrazak Hamdallah": "عبدالرزاق حمدالله",
  "Nedim Bajrami": "نديم باجرامي",
  "Saif Rashad Mohamed": "سيف رشاد محمد",
  "Faris Al Ghamdi": "فارس الغامدي",
  "Mohammed Al Aqel": "محمد العقل",
  "Aschraf El Mahdioui": "أشرف المهديوي",
  "Oscar Dorley": "أوسكار دورلي",
  "Bassem Al-Arini": "باسم العريني",
  "Rakan Altulayhi": "راكان التليهي",
  "Abdulrahman Alsenaid": "عبدالرحمن السنايد",
  "Adeeb Ahmed Al Hassan": "عديب أحمد الحسن",
  "Abdullah Al-Jadani": "عبدالله الجداني",
  "Abdulrahman Ghazzai": "عبدالرحمن غزائي",
  "Al Mufarrij": "المفرج",
  "Abdul Rahman Al Ghamdi": "عبدالرحمن الغامدي",
  "Ibrahim Mahnashi": "إبراهيم مهناشي",
  "Nawaf Mazen Al Hawairy": "نواف مازن الحويري",
  "Nasser Al Haleel": "ناصر الحليل",
  "Mohammed Al Saedi": "محمد السعيدي",
  "Younes El Bahraoui": "يونس البهروي",
  "Jair Collahuazo": "جاير كولاهوازو",
  "Abdulrahman Hendi": "عبدالرحمن هندي",
  "Ibrahim Alzahrani": "إبراهيم الزهراني",
  "Marin Petkov": "مارين بيتكوف",
  "Yafaye Kandé": "يافاي كاندي",
  "Yousef Saleh Al Salem": "يوسف صالح السالم",
  "Awn Al-Saluli": "عون السلولي",
  "Luay Mubarak Al Mohaimeed": "لؤي مبارك المحيميد",
  "Yazan Al Ruwaili": "يزن الروايلي",
  "Saud Al Rashed": "سعود الراشد",
  "Mohamed Amine Ben Hamida": "محمد أمين بن حميدة",
  "Sultan Tanker": "سلطان تانكر",
  "Mohammed Issa": "محمد عيسى",
  "Elton Acolatse": "إلتون أكولاتسي",
  "Mory Konaté": "موري كوناتيه",
  "Afimico Pululu": "أفيميكو بولولو",
  "Amir Sayoud": "أمير سعيد",
  "Waleed Al Shanqiti": "وليد الشنقيطي",
  "Farhan Al-Azmi": "فرحان الأعظمي",
  "Abdullah Al-Shanqiti": "عبدالله الشنقيطي",
  "Bruno Varela": "برونو فاريلا",
  "Bonheur Mugisha": "بونهور موغيشا",
  "Nawaf Al Bishri": "نواف البشري",
  "Amadou Bamba Dieng": "أمادو بامبا دينغ",
  "Abdulaziz Aldhuwayhi": "عبدالعزيز الظويهي",
  "Ibrahim Zaid": "إبراهيم زيد",
  "Aboubacar Bah": "أبوبكر باه",
  "Ahmed Al-Nakhli": "أحمد النخلي",
  "Sofiane Bendebka": "سفيان بندبكا",
  "Aboubacar Diakite": "أبوبكر دياكيتي",
  "Abdulrazzaq Awaji": "عبدالرزاق أواجي",
  "Majed Al Ghamdi": "ماجد الغامدي",
  "Abdurahman Al-Dakheel": "عبدالرحمن الدخيل",
  "Jindrich Stanek": "جيندريش ستانيك",
  "Muhammad Al Darwish": "محمد الدرويش",
  "Ahmed Al-Shamrani": "أحمد الشمراني",
  "Khalid Al Subaie": "خالد الصبائي",
  "Mohammed Turki Al Hamdani": "محمد تركي الحمداني",
  "Abdulaziz Al-Harbi": "عبدالعزيز الحربي",
  "Khalid Faisal Hasan Abduljawad": "خالد فيصل حسن عبدالجواد",
  "Hassan Idris": "حسن إدريس",
  "Jaser Muneer Shleaah Ateeq": "جاسر منير شليح عتيق",
  "Ayman Al Hujaili": "أيمن الحجيلي",
  "Hamed Al-Shanqiti": "حامد الشنقيطي",
  "Chancel Mbemba": "شانسيل مبيمبا",
  "Mathys De Carvalho": "ماثيس دي كارفالو",
  "Lovro Chelfi": "لوفرو تشيلفي",
  "Sultan Alessa": "سلطان عليسة",
  "Yasser Al Musa": "ياسر الموسى",
  "Hossam Majrashi": "حسام مجراشي",
  "Abdul Keita": "عبدالكيتا",
  "Trézéguet": "تريزيغيه",
  "Teddy Okou": "تيدي أوكو",
  "Hassan Hashim Al Ali": "حسن هاشم العلي",
  "Sulaiman Hazazi": "سليمان حزازي",
  "Osama Zaid Abdulaziz Al Bowardi": "أسامة زيد عبدالعزيز البوردي",
  "Essam Bahri": "عصام بحري",
  "Faisal Al Subhi": "فيصل الصباحي",
  "Abdullah Hassuna": "عبدالله حسن",
  "Hussain Al Raqwani": "حسين الرقواني",
  "Khaled Ali": "خالد علي",
  "Hussain Al Shurafaa": "حسين الشرفاء",
  "Tozé": "توزيه",
  "Victor Lekhal": "فيكتور ليخال",
  "Hussain Salem": "حسين سالم",
  "Abdulilah Al Tale": "عبدالله التل",
  "Rodrigo Abascal": "رودريغو أباسكال",
  "Salman Matar": "سلمان مطر",
  "Luca Ramirez": "لوكا راميريز",
  "Bernard Mensah": "برنارد منساه",
  "Majed Al Qahtani": "ماجد القحطاني",
  "Mohammed Alkhaibari": "محمد الخيباري",
  "Leandro Antunes": "لياندرو أنتونيس",
  "Fahad Al Jayzani": "فهد الجيزاني",
  "Milan Borjan": "ميلان بورجان",
  "Yahya Alshehri": "يحيى الشهري",
  "Cheikh Mbacke Modou Fall": "شلال شيخ مباكي مودو",
  "Emad Fidaa": "عماد فداء",
  "Awad Dahal": "عوض دهال",
  "Battal Al Harthi": "بتال الحارثي",
  "Mory Diaw": "موري دياو",
  "Mohammed Al Shwirekh": "محمد الشويرخ",
  "Mamadou Barry": "مامادو باري",
  "Tin Jedvaj": "تين جدفاج",
  "Ali Makki": "علي مكي",
  "Awad Al Nashri": "عوض النشاري",
  "Josh Brownhill": "جوش براونهيل",
  "Roger Martínez": "روجر مارتينيز",
  "Yannick Carrasco": "يانيك كاراسكو",
  "Daniel Podence": "دانيال بودنس",
  "Lazar Stojanovic": "لازار ستويانوفيتش",
  "Mohammed Al Thani": "محمد آل ثاني",
  "Thomas Partey": "توماس بارتي",
  "Dhari Al Anazi": "ضاري العنزي",
  "Hammam Al-Hammami": "حمام الحمامي",
  "Abdulaziz Rahma": "عبدالعزيز رحمة",
  "Abdulrahman Al-Obud": "عبدالرحمن العبود",
  "Abdullah Al Hawsawi": "عبدالله الهوساوي",
  "Yacine Adli": "ياسين عدلي",
  "Mohammed Al Mahasna": "محمد المحسنة",
  "Sultan": "سلطان",
  "Mohammed Essa Harbush": "محمد عيسى هاربوش",
  "Ali Al-Asmari": "علي الأسمري",
  "Ricardo Mathias": "ريكاردو ماثياس",
  "Abdullah Saeed": "عبدالله سعيد",
  "Yazeed Al Dosari": "يزيد الدوسري",
  "Mohammed Al-Otaibi": "محمد العتيبي",
  "Muqrin Abanumay": "مقرن أبانوماي",
  "Abdulaziz Hadhood": "عبدالعزيز حدود",
  "Murad Khadari": "مراد خداري",
  "Hamad Al-Khorayef": "حمد الخريف",
  "Ali Al-Bulayhi": "علي البليحي",
  "Talal Riyadh Al Shubili": "طلال الرياض الشبلي",
  "Adrian Semper": "أدريان سيمبر",
  "Kennedy Boateng": "كينيدي بواتينغ",
  "Ziyad Al Jari": "زياد الجري",
  "Faisal Darisi": "فيصل داريسي",
  "Ali Al-Hassan": "علي الحسن",
  "Fahad Zubaidi": "فهد زبيدي",
  "Mihai Lixandru": "ميهاي ليكساندرو",
  "Wilfried Kanga": "ويلفريد كانغا",
  "Lukás Haraslín": "لوكاس هارسلين",
  "Mourad Batna": "مراد بطنة",
  "Abdulelah Al Khaibari": "عبدالإله الخيباري",
  "Marwane Saadane": "مروان سعدن",
  "Abdulaziz Al Fawaz": "عبدالعزيز الفواز",
  "Robin Kelder": "روبن كيلدر",
  "Hossam Essadak": "حسام الصدق",
  "Jefferson Ramos": "جيفرسون راموس",
  "Abdul Rahman Al Khaibari": "عبدالرحمن الخيباري",
  "João Vitor Oliveira": "جواو فيتور أوليفيرا",
  "Mahdi Al Obod": "مهدي العبود",
  "Mohammed Al-Sahihi": "محمد السهيحي",
  "Zaydou Youssef": "زيدو يوسف",
  "Ali Al Masoud": "علي المسعود",
  "Habib Alwotayan": "حبيب الوتيان",
  "Ibrahim Omar Abdulaziz Al Abood": "إبراهيم عمر عبدالعزيز العبد",
  "Saad Al-Shurafa": "سعد الشرفاء",
  "Muntathir Al Shaqaq": "منتظر الشقاق",
  "Jordan Harrison": "جوردان هاريسون",
  "Abdulaziz Anwar Abdulrahman Al Suwailem": "عبدالعزيز أنور عبدالرحمن السويلم",
  "Faisal Al Abdulwahed": "فيصل عبدالواحد",
  "Sattam Al Tumbukti": "سطام التمبكتي",
  "Othman Ramzi Jasim Al Othman": "عثمان رمزي جاسم العثمان",
  "Waled Al Enazi": "وليد العنزي",
  "Ali Alamine Ali": "علي الأمين علي",
  "Abdulraouf Al Dakheel": "عبدالرؤوف الدخيل",
  "Mukhir Al Rashidi": "مخير الراشدي",
  "Hugo Moura": "هوجو مورا",
  "Ali Al Hussain": "علي الحسين",
  "Nawaf Al-Harthi": "نواف الحارثي",
  "Malek Al Abdulmonam": "مالك عبدالمنعم",
  "Fashion Sakala": "فاشن ساكالا",
  "Turki Al Jaadi": "تركي الجادي",
  "Sattam Al Shammari": "سطام الشمري",
  "Mansor Faiez Al-Beshe": "منصور فايز البشه",
  "Paulo Oliveira": "باولو أوليفيرا",
  "Abdulhadi Al-Harajin": "عبدالهادي الهرجين",
  "Lázaro": "لازارو",
  "Abdullah Al Qahtani": "عبدالله القحطاني",
  "Ziyad Al Sahafi": "زياد السهفي",
  "Mohammed Al Baqawi": "محمد البقاوي",
  "Jason": "جيسون",
  "Ahmed Bamasud": "أحمد باماسود",
  "Omar Colley": "عمر كولي",
  "Sultan Al Jarbi": "سلطان الجربي",
  "Albaraa Addawi": "البراء العدوي",
  "Alfa Semedo": "ألفا سيميدو",
  "Osama Al Thumairy": "أسامة الثميري",
  "Yago Souza": "ياجو سوزا",
  "Ammar Al Khaibari": "عمار الخيباري",
  "Ali Dhafer Saleh Al Harshan": "علي ظافر صالح الحرشان",
  "Fahad Majed Mohammed Alhubayshi": "فهد ماجد محمد الحبيشي",
  "Mohammed Al Dowaish": "محمد الدويش",
  "Orlando Mosquera": "أورلاندو موسكيرا",
  "Abdullah Awadh Khulaif Alanazi": "عبدالله عوض خليف العنزي",
  "Mohammed Ahmed Mohammed Hakami": "محمد أحمد محمد حكامي",
  "Rayan Enad": "ريان عيناد",
  "Mouath Al Habib": "معاذ الحبيب",
  "Fernando Pacheco": "فرناندو باتشيكو",
  "Yaseen Barnawi": "ياسين برناوي",
  "Khalid Al-Harbi": "خالد الحربي",
  "Abdoulaye Seck": "عبدالله سك",
  "Andrei Girotto": "أندريه جيروتو",
  "Jaber Mustafa": "جابر مصطفى",
  "Eid Al Muwallad": "عيد المولد",
  "Yousef Al Shammari": "يوسف الشمري",
  "Flávio": "فلافيو",
  "Ibrahima Ndiaye": "إبراهيما ندياي",
  "Théo Bongonda": "ثيو بونغوندا",
  "André-Jordy Ella": "أندريه-جوردي إيلا",
  "Christian Bassogog": "كريستيان باسوغوغ",
  "Abdullah Almogren": "عبدالله المقرن",
  "Mohamed Al Oqil": "محمد العقل",
  "Alexandre Mendy": "ألكسندر ميندي",
  "Jaime Seoane": "جيمي سيوان",
  "Abdulelah Nassief": "عبدالله ناصيف",
  "Abdulaziz Al-Bishi": "عبدالعزيز البشي",
  "Moayad Saleem": "مؤيد سليم",
  "Mohammed Al-Hasawi": "محمد الحساوي",
  "Dayo Joyce Osho": "دايو جويس أوشو",
  "Wael Hassan Mohammed Kadan": "وائل حسن محمد قدان",
  "Mohammed Al-Shanqiti": "محمد الشنقيطي",
  "Mohammed Jahfali": "محمد جحفلي",
  "Ahmed Abdu": "أحمد عبده",
  "Abdulrahman Al Sharif": "عبدالرحمن الشريف",
  "Hussain Al Zarie": "حسين الزرعي",
  "Abdullah Subayt": "عبدالله سبيت",
  "Saud Haddad": "سعود حداد",
  "Ayman Fallatah": "أيمن فلاتة",
  "Fawaz Rabie": "فواز رابي",
  "Abdulrahman Al Safari": "عبدالرحمن السفاري",
  "Koen Casteels": "كوين كاستيلز",
  "Mohammed Abu Al-Shamat": "محمد أبو الشامت",
  "Jehad Thakri": "جهاد ذكري",
  "Julian Weigl": "جوليان فايغل",
  "Nacho": "ناتشو",
  "Turki Al-Ammar": "تركي العمار",
  "Nahitan Nández": "ناهيتان نانديز",
  "Abdullah Al-Salem": "عبدالله السالم",
  "Musab Al-Juwayr": "مصعب الجوير",
  "Ali Abdullah Hazzazi": "علي عبدالله حزازي",
  "Yasser Al-Shahrani": "ياسر الشهراني",
  "Abdulah Al Jwayzan": "عبدالله الجويزان",
  "Tijjani Reijnders": "تيجاني رايندرز",
  "Mohammed Al-Qahtani": "محمد القحطاني",
  "Gastón Álvarez": "غاستون ألفاريز",
  "Abdulmalik Al Jaber": "عبدالملك الجابر",
  "Haitham Asiri": "هيثم عسيري",
  "Christopher Bonsu Baah": "كريستوفر بونسو باه",
  "Waleed Al-Ahmed": "وليد الأحمد",
  "Mohammed Qasem": "محمد قاسم",
  "Ali Diabaté": "علي دياباتي",
  "Eyad Houssa": "إياد حسى",
  "Ahmed Al-Kassar": "أحمد القصار",
  "Mahamadou Sangaré": "ماهامادو سانغاري",
  "Abgullah Almuhaysin": "عبدالله المحيسين",
  "Mateo Retegui": "ماتيو ريتيغوي",
  "Julián Quiñones": "جوليان كينيونيس",
  "Ahmed Al Siyahi": "أحمد السياهي",
  "Abdulaziz Al-Aliwa": "عبدالعزيز العليوة",
  "Meshari Sunyur": "مشاري سونيور",
  "Wafi Al Aklabi": "وافي الأكلبي",
  "Sani Suleiman": "ساني سليمان",
  "Nawaf Al-Aqidi": "نواف العقيدي",
  "Sultan Al-Ghannam": "سلطان الغنام",
  "Mohamed Simakan": "محمد سيماكان",
  "Nader Al Sharari": "نادر الشراري",
  "Abdulelah Al-Amri": "عبدالإله العمري",
  "Saad Al Nasser": "سعد الناصر",
  "Cristiano Ronaldo": "كريستيانو رونالدو",
  "Hayder Abdulkareem": "حيدر عبدالكريم",
  "Abdullah Al-Hamdan": "عبدالله الحمدان",
  "Sadio Mané": "ساديو ماني",
  "Samú Costa": "سامو كوستا",
  "Nawaf Boushal": "نواف بوشال",
  "Sami Al-Najei": "سامي النجيعي",
  "Mohammed Maran": "محمد مران",
  "Abdullah Al-Khaibari": "عبدالله الخيبري",
  "Ângelo Gabriel": "أنجيلو غابرييل",
  "Kingsley Coman": "كينغسلي كومان",
  "Abdulhadi Al-Alwan": "عبدالهادي العلوان",
  "Aiman Yahya": "أيمن يحيى",
  "Bento": "بينتو",
  "Iñigo Martínez": "إينيغو مارتينيز",
  "Abdulrahman Ghareeb": "عبدالرحمن غريب",
  "Majed Qasheesh": "ماجد قشيش",
  "Abdulrahman Al Otaibi": "عبدالرحمن العتيبي",
  "Rakan Al Ghamdi": "راكان الغامدي",
  "Saad Haqawi": "سعد حقاوي",
  "Mubarak Al Buainain": "مبارك البوعينين",
  "Sultan Abdullah Saad Al Mas": "سلطان عبدالله سعد الماس",
  "Awad Aman": "عوض أمان",
  "João Félix": "جواو فيليكس",
  "Salem Al Najdi": "سالم النجدي",
  "Abdulrahman Sufyani": "عبدالرحمن سفاني",
  "Aser Abdulftah Hwsawi": "آسر عبدالفتاح هوساوي",
  "Mohammed Mahzari": "محمد مهزاري",
  "Kalidou Koulibaly": "كاليدو كوليبالي",
  "Yusuf Akcicek": "يوسف أكسجيك",
  "Nasser Al-Dawsari": "ناصر الدوسري",
  "Gabriel Martinelli": "غابرييل مارتينيلي",
  "Rúben Neves": "روبن نيفيش",
  "Ollie Watkins": "أولي واتكينز",
  "Mohammed Al-Yami": "محمد اليامي",
  "Murad Al Hawsawi": "مراد الهوساوي",
  "Theo Hernández": "ثيو هيرنانديز",
  "Sergej Milinkovic-Savic": "سيرجي ميلينكوفيتش-سافيتش",
  "Moteb Al-Harbi": "متعب الحربي",
  "Sultan Mandash": "سلطان مندش",
  "Mohamed Kanno": "محمد كنو",
  "Salem Al-Dawsari": "سالم الدوسري",
  "Mohammed Al-Owais": "محمد العويس",
  "Rayan Al Dossary": "ريان الدوسري",
  "Yassine Bounou": "ياسين بونو",
  "Crysencio Summerville": "كريسينسيو سومرفيل",
  "Abdulaziz Jurmush": "عبدالعزيز جرموش",
  "Louay Labidi": "لؤي لعبيدي",
  "Saad Khalid Al Muthary": "سعد خالد المطيري",
  "Meshal Al Dawood": "مشعل الداود",
  "Turki Al Ghamil": "تركي الغامدي",
  "Saïmon Bouabré": "سايمون بوابري",
  "Sabri Abdu Dahal": "صبري عبده ضحال",
  "Mohammed Al-Sarnoukh": "محمد السرنوخ",
  "Kader Meïté": "قادر ميتي",
  "Nawaf Al-Habshi": "نواف الحبشي",
  "Ali Lajami": "علي لجامي",
  "Hassan Al-Tambakti": "حسن التمبكتي",
  "Hamad Al-Yami": "حمد اليامي",
  "Abdullah Safoud Alemzi": "عبدالله سعود عليمزي",
  "Thari Saeed": "ذاري سعيد",
  "Suhayb Alzaid": "سهيب الزيد",
  "Marcin Bulka": "مارسين بولكا",
  "Mohammed Al-Burayk": "محمد البريك",
  "Khalifah Al-Dawsari": "خليفة الدوسري",
  "Malang Sarr": "مالانغ سار",
  "Abbas Al Hassan": "عباس الحسن",
  "Georgios Masouras": "جورجيوس ماسوراس",
  "Faisal Al-Ghamdi": "فيصل الغامدي",
  "Abdulaziz Al Othman": "عبدالعزيز العثمان",
  "Saïd Benrahma": "سعيد بن رحمة",
  "Khalil Al-Absi": "خليل العبسي",
  "Abdulmalik Al Oyayari": "عبدالملك العياري",
  "Ala Al-Hajji": "علاء الحاجي",
  "Mohannad Abu Taha": "مهند أبو طه",
  "Ahmed Al Anazi": "أحمد العنزي",
  "Valentin Vada": "فالنتين فادا",
  "Abdulaziz Noor": "عبدالعزيز نور",
  "Islam Hawsawi": "إسلام هوساوي",
  "Abdulrhman Daghreeri": "عبدالرحمن داغرياري",
  "Nathan Zeze": "ناثان زيزي",
  "Mohammed Al Dossari": "محمد الدوسري",
  "Haroune Camara": "هارون كامارا",
  "Amadou Koné": "أمادو كوني",
  "Khalid Al Rammah": "خالد الرماح",
  "Muhannad Al-Saad": "مهند السعد",
  "Luís Maximiano": "لويس ماكسيميانو",
  "Alexandre Lacazette": "ألكسندر لاكازيت",
  "Farhah Al Shamrani": "فرحة الشمراني",
  "Dion Lopy": "ديون لوبي",
  "Ahmed Al-Julaydan": "أحمد الجليدان",
  "Steven Bergwijn": "ستيفن بيرغوين",
  "Mohammed Fallatah": "محمد فلاتة",
  "Mohammed Alabsi": "محمد العبسي",
  "Rakan Kaabi": "راكان كعبي",
  "Mohammed Ali Barnawi": "محمد علي برناوي",
  "Hamed Alghamdi": "حامد الغامدي",
  "Osama Al Marwash": "أسامة المروش",
  "Marek Rodák": "مارك روداك",
  "Abdullah Madu": "عبدالله مادو",
  "Jack Hendry": "جاك هندري",
  "Khalid Al-Ghannam": "خالد الغنام",
  "Moussa Dembélé": "موسى ديمبيلي",
  "Álvaro Medrán": "ألفارو مدران",
  "Ondrej Duda": "أوندريه دودا",
  "Meshal Alaeli": "مشعل عليلي",
  "Abdullah Al Bishi": "عبدالله البشي",
  "Mohammed Alkadi": "محمد القدي",
  "Jordan Larsson": "جوردان لارسون",
  "Abdulhakim Maghfori": "عبدالحكيم مغفوري",
  "Ahmad Al-Harbi": "أحمد الحربي",
  "Jalal Al Salem": "جلال السالم",
  "Abdullah Al Ghamdi": "عبدالله الغامدي",
  "Madallah Al-Olayan": "مدالله العليان",
  "Abdoulaye Kanté": "عبدالله كانتي",
  "Bersant Celina": "بيرسانت سيلينا",
  "Yasir Shammari": "ياسر الشمري",
  "Radhi Al-Otaibi": "راضي العتيبي",
  "Abdullah Khateeb": "عبدالله خطيب",
  "Matija Gluscevic": "ماتيا غلوشيفيتش",
  "Abdulelah Hawsawi": "عبدالإله هوساوي",
  "Marzouq Tambakti": "مرزوق تمبكتي",
  "Rayane Messi": "رايان ميسي",
  "Meshal Sibyani": "مشعل السيبياني",
  "Ali Mohsen Abdullah Al Essa": "علي محسن عبدالله العيسى",
  "Turki Baaljawsh": "تركي بعلجوش",
  "Pedro Henrique": "بيدرو هنريكي",
  "Riyadh Sharahili": "رياض شراحيلي",
  "Talal Haji": "طلال حاجي",
  "Sultan Ali Harun": "سلطان علي هارون",
  "Abdulrahman Al-Sanbi": "عبدالرحمن السنبي",
  "Zakaria Al Hawsawi": "زكريا الهوساوي",
  "Roger Ibañez": "روجر إيبانيز",
  "Makaya Diaby": "ماكايا ديابي",
  "Mohammed Sulaiman": "محمد سليمان",
  "Valentin Atangana": "فالنتين أتانجانا",
  "Juriën Gaari": "جورين غاري",
  "Basil Yousef Al-Sayyali": "باسل يوسف السيالي",
  "Faisal Al Sibyani": "فيصل السيبياني",
  "Feras Al Ghamdi": "فراس الغامدي",
  "Nasser Al-Daajani": "ناصر الدعجاني",
  "Kamil Boumedmed": "كامل بومدين",
  "Nabil Fekir": "نبيل فقير",
  "Alimani Gory": "عليماني غوري",
  "Khaled Al Shamrani": "خالد الشمراني",
  "Georges-Kévin N'Koudou": "جورج-كيفن نكودو",
  "Donovan Léon": "دونوفان ليون",
  "Moayad Mohammed Ahmad Binyan": "مؤيد محمد أحمد بنيان",
  "Abdulkarim Darisi": "عبدالكريم دارسي",
  "Mohammed Al Hamsal": "محمد الحمسال",
  "Abdullah Al Fahad": "عبدالله الفهد",
  "Koshaim Al Karani": "كوشيم الكراني",
  "Abdulrahman Al Bouq": "عبدالرحمن البوق",
  "Abdou Diallo": "عبدو ديالو",
  "Mohammad Al-Dawsari": "محمد الدوسري",
  "Mustafa Malaika": "مصطفى مليكة",
  "Bader Al Mutairi": "بدر المطيري",
  "Majed Dawran": "ماجد دوران",
  "Loreintz Rosier": "لورينتز روزييه",
  "Abdulbasit Hindi": "عبدالباسط الهندي",
  "Mohammed Al Zaid": "محمد الزايد",
  "Michy Batshuayi": "ميتشي باتشواي",
  "Nawaf Al Ghulaimish": "نواف الغليمش",
  "Safwan Saud S": "صفوان سعود",
  "Amar Al Yuhaybi": "عمار اليحيبي",
  "Mateo Borrell": "ماتيو بوريل",
  "Predrag Rajkovic": "بريدراج رايكوفيتش",
  "Danilo Pereira": "دانيلو بيريرا",
  "Jan-Carlo Simic": "يان-كارلو سيميتش",
  "Richard Ríos": "ريتشارد ريوس",
  "Saad Al Mosa": "سعد الموسى",
  "Roger Fernandes": "روجر فرنانديز",
  "Mukhtar Ali": "مختار علي",
  "George Ilenikhena": "جورج إيلينخينا",
  "Houssem Aouar": "حسام عوار",
  "Saleh Al-Shehri": "صالح الشهري",
  "Muhannad Al-Shanqiti": "مهند الشنقيطي",
  "Hassan Kadish": "حسن كاديش",
  "Mahamadou Doumbia": "ماهامادو دومبيا",
  "Ahmed Sharahili": "أحمد شراحيلي",
  "Youssef En-Nesyri": "يوسف النصيري",
  "Marwan Al-Sahafi": "مروان الصحفي",
  "Georginio Wijnaldum": "جورجينيو فينالدوم",
  "Abdi Faris": "عبدي فارس",
  "Ahmed Al Ghamdi": "أحمد الغامدي",
  "Edgaras Utkus": "إدغاراس أوتكوس",
  "John Buckley": "جون باكلي",
  "Sultan Al-Shehri": "سلطان الشهري",
  "Seydouba Cissé": "سيدوبا سيسي",
  "Iker Kortajarena": "إيكر كورتاجارينا",
  "Coba da Costa": "كوبا دا كوستا",
  "Ibrahem Barabaa": "إبراهيم بارابا",
  "Ramzi Solan": "رمزي سولان",
  "Adam Berry": "آدم بيري",
  "Ramiro Enrique": "راميرو إنريكي",
  "Salman Al Mosawa": "سلمان الموساوي",
  "Julien Domingues": "جوليان دومينغ",
  "Yazan Madani": "يزن مدني",
  "Adi": "آدي",
  "Mansour Camara": "منصور كامارا",
  "Yaseen Al Zubaidi": "ياسين الزبيدي",
  "Abdullah Al Ajyan": "عبدالله العجيان",
  "Mohammed Alshammari": "محمد الشمري",
  "Fares Bandar Al Zahrani": "فارس بندر الزهراني",
  "Shaquille Pinas": "شاكيل بيناس",
  "Abdulrahman Al-Dossari": "عبدالرحمن الدوسري",
  "Abdulrahman Al Obaid": "عبدالرحمن العبيد",
  "Abdulmalik Al Harbi": "عبدالملك الحربي",
  "Muhannad Al Yahya": "مهند اليحيى",
  "Rakan Jaman": "راكان جامان",
  "Mohammed Al Rashdi": "محمد الرشدي",
  "Muhammad Sawan": "محمد ساوان",
  "Antoin Bikoula": "أنطوان بيكولا",
  "Anas Al Otaibi": "أنس العتيبي",
  "Guga": "غوغا",
  "Mohammed Ibrahim": "محمد إبراهيم",
  "Hamad Al Jayzani": "حمد الجيزاني",
  "Mohammed Khubrani": "محمد خوبراني",
  "Boubakar Kiki Kouyate": "بوبكر كيكي كوياتي",
  "Rebocho": "ريبوتشو",
  "Joshua King": "جوشوا كينغ",
  "Omar Mascarell": "عمر ماسكاريل",
  "Angelo Fulgini": "أنجيلو فولجيني",
  "Saleh Al-Jamaan": "صالح الجمال",
  "Majed Kanabah": "ماجد كنابة",
  "Ahmad Asiri": "أحمد عسيري",
  "Ali Al Shaafi": "علي الشافي",
  "Mansour Hamzi": "منصور حمزي",
  "Bader Munshi": "بادر منشي",
  "Abdullah Al Hafith": "عبدالله الحفيث",
  "Nawaf Al Saadi": "نواف السعدي",
  "Miguel Silva": "ميغيل سيلفا",
  "Mohammed Al Abdullah": "محمد آل عبدالله",
  "Wilson Diogo Monteiro Da Cruz": "ويلسون دييغو مونتيرو دا كروز",
  "Ali Abdoulraouf Alabdrabalnabi": "علي عبدالرؤوف عبدالنبي",
  "Hamid Al Zahri": "حميد الزهري",
  "Raed Firas Al Shanqiti": "رائد فراس الشنقيطي",
  "Fawaz Al Saqour": "فواز الصقور",
  "Hussain Ahmed Al Issa": "حسين أحمد العيسى",
  "Saeed Al Hamsal": "سعيد الحمسال",
  "Anthony Moris": "أنتوني موريس",
  "Abdoulie Mboge": "عبدولي مبوغ",
  "Qassim Mutawaa": "قاسم مطوية",
  "Thamer Al Khaibri": "ثامر الخيبري",
  "Abdulrahman Al Triki": "عبدالرحمن التركي",
  "Abdulmajeed Al Khathami": "عبدالمجيد الخاتمي",
  "Ziyad Hantoul": "زياد هنتول",
  "Sajjad Al Akieli": "سجاد العكيلي",
  "Marwan Al Haidari": "مروان الحيداري",
  "Sultan Al Dossari": "سلطان الدوسري",
  "Al Hassan Al Dubais": "الحسن الدبيز",
  "Musa Barrow": "موسى بارو",
  "Abdullah Al-Amar": "عبدالله العمار",
  "Fahad Alrashidi": "فهد الراشدي",
  "Mateo Benegas": "ماتيو بينيغاس",
  "Abdulaziz Al Faraj": "عبدالعزيز الفراج",
  "Saeed Al-Rabiei": "سعيد الربيعي",
  "Idrissa Gueye": "إدريسا غي",
  "Sultan Al Farhan": "سلطان الفرحان",
  "Ziyad Al Qahtani": "زياد القحطاني",
  "Gaëtan Laborde": "غايتان لابورد",
  "Adil Boulbina": "عادل بولبينا",
  "Hatan Bahbri": "هاتان باهبري",
  "Taher Wadi": "طاهر وادي",
  "Óscar Rodríguez": "أوسكار رودريغيز",
  "Hussain Al-Sabiyani": "حسين السبياني",
  "Clayton Diandy": "كلايتون دياني",
  "Berat Djimsiti": "بيرات جيمسيتي",
  "Abdulelah Al Jaaferi": "عبدالإله الجعفري",
  "Enzo Millot": "إنزو ميلو",
  "Mohamed Thaiban Hameran": "محمد ذيبان حميران",
  "Mohammed Dheban": "محمد ذيبان",
  "Nikola Vasilj": "نيكولا فاسيلي",
  "Muteb Sharahili": "متعب شراحيلي",
  "Fahad Al Obaid": "فهد العبيد",
  "Darwin Núñez": "داروين نونيز",
  "Abdullah Al Zaid": "عبدالله الزايد",
  "Waleed Ali": "وليد علي",
  "Mansour Hibatullah Al Sibyani": "منصور هبة الله السيبياني",
  "Hussain Al-Qahtani": "حسين القحطاني",
  "Meshari Al Nemer": "مشاري النمر",
  "Khalid Al Asiri": "خالد العسيري",
  "Qassem Lajami": "قاسم لجامي",
  "Abdulelah Al-Malki": "عبدالإله المالكي",
  "Ameen Al-Bukhari": "أمين البخاري",
  "Mubarak": "مبارك"
};
 
};

window.translatePlayer = function(name) {
  if (!name) return '';
  if (playerNames[name]) return playerNames[name];
  var lower = name.toLowerCase();
  for (var k in playerNames) {
    if (k.toLowerCase() === lower) return playerNames[k];
  }
  return name;
};
